name: Build (Windows / MinGW-GCC)
description: Configure, build, test, and optionally package axidev-io on Windows using MinGW-w64 GCC (linked against libstdc++).

inputs:
  arch:
    description: MinGW platform (x64 or x86)
    required: true
  build-type:
    description: CMake build type
    required: false
    default: Release
  build-tests:
    description: Enable unit/integration test targets
    required: false
    default: "false"
  build-integration-tests:
    description: Enable integration tests (AXIDEV_IO_BUILD_INTEGRATION_TESTS)
    required: false
    default: "false"
  run-tests:
    description: Run ctest after build
    required: false
    default: "false"
  package-output:
    description: Install to dist/ and package into packages/
    required: false
    default: "false"
  upload-binaries:
    description: Upload built test binaries as artifacts
    required: false
    default: "false"
  artifact-name:
    description: Artifact name (required when upload-binaries=true)
    required: false
  cmake-generator:
    description: Optional CMake generator override
    required: false
    default: ""
  version:
    description: Release version override (otherwise uses tag ref)
    required: false
    default: ""

runs:
  using: composite
  steps:
    - name: Set MinGW-w64 environment
      id: setup
      shell: bash
      run: |
        if [ "${{ inputs.arch }}" = "x86" ]; then
          echo "msystem=MINGW32" >> $GITHUB_OUTPUT
          echo "prefix=mingw-w64-i686" >> $GITHUB_OUTPUT
        else
          echo "msystem=MINGW64" >> $GITHUB_OUTPUT
          echo "prefix=mingw-w64-x86_64" >> $GITHUB_OUTPUT
        fi

    - name: Setup MSYS2 with MinGW-w64 GCC
      uses: msys2/setup-msys2@v2
      with:
        msystem: ${{ steps.setup.outputs.msystem }}
        update: true
        install: >-
          ${{ steps.setup.outputs.prefix }}-gcc
          ${{ steps.setup.outputs.prefix }}-cmake
          ${{ steps.setup.outputs.prefix }}-ninja
          make

    - name: Clean stale build directory
      shell: msys2 {0}
      run: rm -rf build dist packages

    - name: Configure (CMake)
      shell: msys2 {0}
      run: |
        set -euo pipefail
        BUILD_TYPE='${{ inputs.build-type }}'

        CMAKE_ARGS=(-S . -B build -DCMAKE_BUILD_TYPE="$BUILD_TYPE")

        if [ -z '${{ inputs.cmake-generator }}' ]; then
          CMAKE_ARGS+=( -G 'Ninja' )
        else
          CMAKE_ARGS+=( -G '${{ inputs.cmake-generator }}' )
        fi

        if [ '${{ inputs.build-tests }}' = 'true' ]; then
          CMAKE_ARGS+=( -DAXIDEV_IO_BUILD_TESTS=ON )
        fi

        if [ '${{ inputs.build-integration-tests }}' = 'true' ]; then
          CMAKE_ARGS+=( -DAXIDEV_IO_BUILD_INTEGRATION_TESTS=ON )
        fi

        # Statically link libstdc++/libgcc to avoid MinGW runtime DLL dependencies
        CMAKE_ARGS+=( -DAXIDEV_IO_MINGW_STATIC_RUNTIME=ON )

        cmake "${CMAKE_ARGS[@]}"

    - name: Build (CMake)
      shell: msys2 {0}
      run: |
        set -euo pipefail
        cmake --build build --config '${{ inputs.build-type }}' --parallel

    - name: Run tests (ctest)
      if: ${{ inputs.run-tests == 'true' }}
      shell: msys2 {0}
      env:
        CTEST_OUTPUT_ON_FAILURE: 1
      run: |
        set -euo pipefail
        ctest --test-dir build --output-on-failure -C '${{ inputs.build-type }}'

    - name: Install
      if: ${{ inputs.package-output == 'true' }}
      shell: msys2 {0}
      run: |
        set -euo pipefail
        cmake --install build --prefix dist --config '${{ inputs.build-type }}'

    - name: Package (Windows)
      if: ${{ inputs.package-output == 'true' }}
      shell: pwsh
      run: |
        $tag = "${{ inputs.version }}"
        if (-not $tag) {
          $tag = $env:GITHUB_REF -replace '^refs/tags/', ''
        }
        New-Item -ItemType Directory -Path packages -Force | Out-Null
        Compress-Archive -Path "dist\*" -DestinationPath "packages/axidev-io-$tag-windows-${{ inputs.arch }}.zip" -Force

    - name: Upload release package
      if: ${{ inputs.package-output == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: release-package-windows-${{ inputs.arch }}
        path: packages/*.zip

    - name: Upload test binaries
      if: ${{ inputs.upload-binaries == 'true' }}
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: |
          build/tests/axidev-io-unit-tests*
          build/tests/axidev-io-integration-tests*
